### ISSUE TITLE
HiddenEye, problem of execution.

### ISSUE THREAD

**Issue by Arcai666333999** [Soldie/HiddenEye-DarkSecDevelopers#1]
when i try to run hiddeneye, i get this error
Traceback (most recent call last):
  File "./HiddenEye.py", line 8, in <module>
    from Defs.Checks import *
  File "/home/netstorm/Desktop/HackTool/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'

**Comment by cringyman** [comment]
Try to install wget using pip

**Comment by Warhammar** [comment]
Use Sudo
